language: node_js
node_js: 
    - '11'
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git config user.name "${USERNAME}"
  - git config user.email "${UESREMAIL}"
  - git add -A
  - git commit -m "New Site"
  - git push --force  "https://github.com/zhufengnodejs/zhufeng_typescript_development.git" "gh-pages" 